# Generated by Django 5.1.1 on 2024-09-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
