# Generated by Django 5.1.1 on 2024-09-07 23:34

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_individual_country_individual_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
